import type { Service } from '@/types';

export const demoServices: Service[] = [
  {
    id: 'e1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6',
    name: 'Certidão de Nascimento',
    name_kr: 'Sertidun di Nasimentu',
    category: 'Registo Civil',
    description: 'Emissão de certidão de nascimento para cidadãos guineenses.',
    requirements: ['código ID', 'Testemunha maior de idade', 'Dados dos pais'],
    estimated_days: 5,
    fee_xof: 0,
    available_offline: true,
    ussd_code: '*244*1*1#',
  },
  {
    id: 'e2b3c4d5-e6f7-a8b9-c0d1-e2f3a4b5c6d7',
    name: 'Registo de Terreno',
    name_kr: 'Registu di Teru',
    category: 'Propriedade',
    description: 'Registo de propriedade de terreno com geolocalização.',
    requirements: ['código ID', 'Localização GPS', 'Aprovação do Régulo'],
    estimated_days: 30,
    fee_xof: 5000,
    available_offline: true,
    ussd_code: '*244*1*2#',
  },
  {
    id: 'e3c4d5e6-f7a8-b9c0-d1e2-f3a4b5c6d7e8',
    name: 'Consulta Médica',
    name_kr: 'Konsulta Médiku',
    category: 'Saúde',
    description: 'Agendamento de consulta médica no centro de saúde regional.',
    requirements: ['código ID'],
    estimated_days: 3,
    fee_xof: 0,
    available_offline: false,
    ussd_code: '*244*2*1#',
  },
  {
    id: 'e4d5e6f7-a8b9-c0d1-e2f3-a4b5c6d7e8f9',
    name: 'Cartão de Vacinação',
    name_kr: 'Kartun di Vasinason',
    category: 'Saúde',
    description: 'Emissão de cartão de vacinação digital.',
    requirements: ['código ID', 'Registos de vacinação'],
    estimated_days: 1,
    fee_xof: 0,
    available_offline: true,
    ussd_code: '*244*2*2#',
  },
  {
    id: 'e5e6f7a8-b9c0-d1e2-f3a4-b5c6d7e8f9a0',
    name: 'Matrícula Escolar',
    name_kr: 'Matríkula Skolar',
    category: 'Educação',
    description: 'Inscrição em escola pública da região.',
    requirements: ['código ID', 'Certidão de Nascimento', 'Dados do encarregado'],
    estimated_days: 7,
    fee_xof: 0,
    available_offline: true,
    ussd_code: '*244*3*1#',
  },
  {
    id: 'e6f7a8b9-c0d1-e2f3-a4b5-c6d7e8f9a0b1',
    name: 'Licença de Pesca',
    name_kr: 'Lisensa di Peska',
    category: 'Economia',
    description: 'Licença para pesca artesanal costeira.',
    requirements: ['código ID', 'Registo de embarcação'],
    estimated_days: 14,
    fee_xof: 10000,
    available_offline: false,
    ussd_code: '*244*4*1#',
  },
];
